### ISSUE TITLE
No module named '_ext'

### ISSUE THREAD

**Issue by obouluh** [zhang-tao-whu/e2ec#1]
when i run test.py show the error:
python=3.7 
![image](https://user-images.githubusercontent.com/22076064/161201303-c35283a8-96e5-4e24-84be-a70cc7e0bf68.png)

and i think the same one like https://github.com/CharlesShang/DCNv2/issues/24.
can u help me to solve this problem?
Thanks！

**Comment by zhang-tao-whu** [comment]
When you use the `conda list` to view the environment, does it show that the dcn has been successfully installed
![dcn](https://user-images.githubusercontent.com/79845037/161225023-78eb7a32-b1af-48d3-8f8d-c37bc61ad048.png)

**Comment by BangwenHe** [comment]
Hi, @obouluh. I use DCNv2 from [lbin/DCNv2](https://github.com/lbin/DCNv2) which contains several torch versions. I use torch1.7 and successfully build DCNv2. If that repo doesn't fit your requirement, you can also try [jinfagang/DCNv2_latest](https://github.com/jinfagang/DCNv2_latest).

**Comment by zhang-tao-whu** [comment]
Hi, I found that using mmcv.ops.ModulatedDeformConv2dPack instead of DCNv2 can also load pre-training weights without any problems. And mmcv-full is very easy to be installed. You can try it. @obouluh
