### ISSUE TITLE
How to set batchsize for each dataset?

### ISSUE THREAD

**Issue by nianshaoyouweibuzibei** [zhang-tao-whu/e2ec#10]

**Comment by zhang-tao-whu** [comment]
By setting the value of --bs. For example, the command for training with a batch size of 24 is `python train_net.py sad --bs 24`; the command for training with a batch size of 16 is `python train_net.py sad --bs 16`.

**Comment by nianshaoyouweibuzibei** [comment]
Sorry, my expression may be wrong. What I want to ask is the batchsize of each dataset
