### ISSUE TITLE
When will the multi GPU training codes be released?

### ISSUE THREAD

**Issue by SSSHZ** [zhang-tao-whu/e2ec#11]
Thanks for your excellent work! 
I wonder when the **multi GPU training codes** will be released, which is very important for reproduction and consequent research. 
I really appreciate your generosity and kindness.

**Comment by zhang-tao-whu** [comment]
By the end of next week at the latest. Please wait a few days.

**Comment by SSSHZ** [comment]
Thank you for all your hard work!

**Comment by zhang-tao-whu** [comment]
Hi, multi GPUS training is supported.
