### ISSUE TITLE
`num_workers=batch_size` in function `make_ddp_train_loader()` in dataset/data_loader.py?

### ISSUE THREAD

**Issue by yeshwanth95** [zhang-tao-whu/e2ec#14]
In the file dataset/data_loader.py, you have set `num_workers=batch_size` in the function `make_ddp_train_loader`. Is there any specific reason for this? You mentioned in issue #13 that you've done this for convenience. Can you please elaborate on this?

This looks like it should instead be `num_workers=train.cfg.num_workers`. Please let me know if this is correct.

Thank you!

**Comment by zhang-tao-whu** [comment]
Yes, you are right. I will fix the problem.
