### ISSUE TITLE
About slow convergence

### ISSUE THREAD

**Issue by CSHran** [zhang-tao-whu/e2ec#16]
Thank you very much for your work, do you know why this method needs to train more than 100 epochs, the convergence speed is very slow, which makes training a lot of inconvenience, some instance segmentation methods only need more than 20 epochs, is it because of CenterNet?

**Comment by zhang-tao-whu** [comment]
Yes, I think so. I tried to build E2EC based on FCOS and achieved good performance after 12 epochs of training on COCO.
