### ISSUE TITLE
Pretrained models url error

### ISSUE THREAD

**Issue by BangwenHe** [zhang-tao-whu/e2ec#2]
Hi, thanks for your wonderful work. But I found a bug in your README file. In the H3 title, `Testing on COCO`, the pretrained model URL should be `gpcv.whu.edu.cn/member/ZhangTao/model.zip`. However, Github converts it into a relative link in your repo, resulting in a 404 page. You can add `https://` ahead of your pretrained model URL to avoid it.

**Comment by zhang-tao-whu** [comment]
Thank you for your suggestion. @BangwenHe. All the pertained model URLs in README.md have been corrected.
