### ISSUE TITLE
Deadlock at Epoch 20

### ISSUE THREAD

**Issue by chenbys** [zhang-tao-whu/e2ec#21]
Thanks for the excellent paper and code. 
But my experiments (DCN disabled) on KINS dataset always deadlock at epoch 20 with GPU and CPU busy.
I use command `python -m torch.distributed.launch --nproc_per_node 2 train_net_ddp.py --config_file kitti --bs 4 --gpus 2`.
Is there any advice to check? Thanks advance.

BTW, what are the minimum bs and epoch in KINS dataset? Bs 64 and epoch 150 seem too huge.

![3](https://user-images.githubusercontent.com/17328133/194736130-8d5f1784-a6ba-4136-832a-2f2ae87f4f99.png)

![1](https://user-images.githubusercontent.com/17328133/194736119-4c95a7d6-ddf9-4c0d-878d-0dfa7a44d832.png)

![2](https://user-images.githubusercontent.com/17328133/194736127-e71b5a3e-210b-4d71-8b9a-8ec4d20d1d36.png)

**Comment by zhang-tao-whu** [comment]
The current version of the code may have this bug when using ddp, and I don't know what causes it. I rebuilt E2EC based on mmdetection, using FCOS as the detector to achieve more robust performance and faster convergence. The code will be released soon.

**Comment by comingsoon1204** [comment]
> The current version of the code may have this bug when using ddp, and I don't know what causes it. I rebuilt E2EC based on mmdetection, using FCOS as the detector to achieve more robust performance and faster convergence. The code will be released soon.
Hello, I am looking forward to your latest work, and thank you for your research. I am looking forward to your latest Fcos implementation. Now the training convergence is a little slow, I would like to take the liberty of asking how long it will be uploaded, I can't wait to try. Thanks!

**Comment by hannn0919** [comment]
> The current version of the code may have this bug when using ddp, and I don't know what causes it. I rebuilt E2EC based on mmdetection, using FCOS as the detector to achieve more robust performance and faster convergence. The code will be released soon.

Hello, thanks for your work. I wonder when you will release the version of FCOS?

**Comment by zhang-tao-whu** [comment]
I used mmdet to re-implement e2ec, no lockups when using ddp, hope this helps you. [e2ec_mmdet](https://github.com/zhang-tao-whu/e2ec_mmdet/tree/master/configs/e2ec).

**Comment by huyuxiao6** [comment]
Do you have the model that is trained already?Because my computer's discrete graphics is not very good, I can't train it, and I want to see the outcome of your model.
