### ISSUE TITLE
Different architectures for polygon refinement?

### ISSUE THREAD

**Issue by chenbys** [zhang-tao-whu/e2ec#22]
The model actually produces five polygons: **init, coarse, final1, final2, and final3**.
**Coarse** is refined using the proposed global deformation module, while **final*** are refined using the circular convolution module.
What if we use all global deformation modules or circular convolution modules for all the polygon refinement?

**Comment by zhang-tao-whu** [comment]
Fine segmentation results require more attention to local information, if only global deformation is used, the predicted results may have poor contour detail quality.
