### ISSUE TITLE
Question about Multi-direction alignment (MDA)

### ISSUE THREAD

**Issue by hannn0919** [zhang-tao-whu/e2ec#24]
Thanks for your work!
But I am confused about the Multi-direction alignment (MDA) part, can you explain in more detail? 
Which part of the code does the MDA correspond to? If I want to try to change the value of M, where should I adjust it?

**Comment by zhang-tao-whu** [comment]
You can read the 76-77 lines of the code in dataset/train/base.py.  If you want to try to change the value of M, you need to implement the new sampling function (you can refer to four_idx) for the alignment point.

**Comment by hannn0919** [comment]
Thanks for your reply!
