### ISSUE TITLE
About detector

### ISSUE THREAD

**Issue by hannn0919** [zhang-tao-whu/e2ec#25]
Hi, thanks for your excellent work!

I tried to train this work on COCO dataset, but it converges very slowly and needs to train more than 100 epochs.
I notice that you mention it is because of CenterNet(detector) in previous issue, and you rebuild this network in FCOS version.

I wonder when will the FCOS version be released? 
Or can you explain how do I change the detector? Which files and what functions should I change?
Thanks! :)

**Comment by zhang-tao-whu** [comment]
Hi!
I have implemented the fcos-based e2ec using mmdetection, and incorporates some minor improvements. Training 12 epochs without data augmentation on coco can achieve 32.9 AP on coco-val, and using data augmentation and training 48 epochs can achieve 35.1 AP on coco-val. You can [e2ec_mmdet]visit [e2ec_mmdet](https://github.com/zhang-tao-whu/e2ec_mmdet/tree/master/configs/e2ec). The config file is e2ec_fcos_center-normbbox-centeronreg-giou_r50_caffe_fpn_gn-head_dcn_feature64_FPNinit_p4evolve_bounddml_wholeInstance_reuniform_mspoints_attentive_normed-rela-coords_1x_coco.py and e2ec_fcos_center-normbbox-centeronreg-giou_r50_caffe_fpn_gn-head_dcn_feature64_FPNinit_p4evolve_bounddml_wholeInstance_reuniform_mspoints_attentive_normed-rela-coords_mstrain_4x_coco.py.
You need to compile some components under csrc before you can use them.
I don't have time to organize the code, so it may be difficult for you to read.

**Comment by hannn0919** [comment]
Really appreciate your reply and patience!!!
I'll try to handle this.
Thanks again. :)
