### ISSUE TITLE
KeyError: 'dla.dla_up.ida_0.proj_1.conv.conv_offset.weight'

### ISSUE THREAD

**Issue by yufeng89** [zhang-tao-whu/e2ec#26]
Traceback (most recent call last):
  File "visualize.py", line 123, in <module>
    run_visualize(cfg)
  File "visualize.py", line 103, in run_visualize
    load_network(network, args.checkpoint)
  File "/e2ec/train/model_utils/utils.py", line 63, in load_network
    net_weight.update({key: pretrained_model[key]})
KeyError: 'dla.dla_up.ida_0.proj_1.conv.conv_offset.weight'

python visualize.py coco /e2ec/images --checkpoint /e2ec/model_cityscapes.pth  --with_nms True --output_dir /e2ec/results
problem is above,load weight has occured problem?

**Comment by yufeng89** [comment]
I've solved,thanks

**Comment by NiteCat-zr** [comment]
I also encountered this problem, how did you solve it?

**Comment by yufeng89** [comment]
模型没对应上，导致权重不匹配。




余风
***@***.***



&nbsp;




------------------&nbsp;原始邮件&nbsp;------------------
发件人:                                                                                                                        "zhang-tao-whu/e2ec"                                                                                    ***@***.***&gt;;
发送时间:&nbsp;2023年4月6日(星期四) 上午9:27
***@***.***&gt;;
***@***.***&gt;;"State ***@***.***&gt;;
主题:&nbsp;Re: [zhang-tao-whu/e2ec] KeyError: 'dla.dla_up.ida_0.proj_1.conv.conv_offset.weight' (Issue #26)





 
I also encountered this problem, how did you solve it?

**Comment by zhang-tao-whu** [comment]
You can refer to #23.
