### ISSUE TITLE
HI, sir

### ISSUE THREAD

**Issue by Wooho-Moon** [zhang-tao-whu/e2ec#31]
sir, 2 days ago, I saw the project related to DVIS, but now, I cannot found that repository.. :( Do you have any plan to reopen that project?

**Comment by zhang-tao-whu** [comment]
Thanks for your attention. I'm sorry for the inconvenience, but due to the company's need for code review, I have temporarily set the repository as private. This will take less than a week. After the review is completed, I will set the repository back to public again.

**Comment by zhang-tao-whu** [comment]
DVIS has been reset to public.
