### ISSUE TITLE
cityscapes_anno.tar.gz show that the link has expired

### ISSUE THREAD

**Issue by cinkyzhang** [zhang-tao-whu/e2ec#35]
Hi, thank you for your work! Could you update the download link of cityscapes_anno.tar.gz file?  Now click on it to show that the link has expired.

   Thank you!

**Comment by zhang-tao-whu** [comment]
Ok, I'll search for it and will provide it to you shortly.

**Comment by zhang-tao-whu** [comment]
You can get it [here](https://drive.google.com/file/d/1hj1um8EE8SuJQhEWvmI-d8rkJe-AEVpi/view?usp=sharing).

**Comment by cinkyzhang** [comment]
OK,Thank you very much.




1710102193
***@***.***



&nbsp;




------------------&nbsp;原始邮件&nbsp;------------------
发件人:                                                                                                                        "zhang-tao-whu/e2ec"                                                                                    ***@***.***&gt;;
发送时间:&nbsp;2023年8月30日(星期三) 晚上7:54
***@***.***&gt;;
***@***.******@***.***&gt;;
主题:&nbsp;Re: [zhang-tao-whu/e2ec] cityscapes_anno.tar.gz show that the link has expired (Issue #35)





 
You can get it here.
