### ISSUE TITLE
系统问题

### ISSUE THREAD

**Issue by Ma-PC** [zhang-tao-whu/e2ec#37]
您好，我是新手，请问您的代码是基于Linux的吗

**Comment by zhang-tao-whu** [comment]
是的

**Comment by Ma-PC** [comment]
有windows版本吗，报错好多

**Comment by zhang-tao-whu** [comment]
如果你可以在windows上成功的安装mmdetection2，你可以使用这个[仓库](https://github.com/zhang-tao-whu/e2ec_mmdet)。
