### ISSUE TITLE
Thanks for your wonderful work!Everything was successful until I tested on coco test-dev set ,returned AP and AR showed to be -1.I don't know the reason.Wish for your answer,thanks.

### ISSUE THREAD

**Issue by thy678** [zhang-tao-whu/e2ec#4]
![image](https://user-images.githubusercontent.com/90585685/164459568-6fa3bdd8-b59e-4891-9ef1-90221cdfcfad.png)

**Comment by zhang-tao-whu** [comment]
The coco-test dataset has no publicly available annotation. You need to submit the `./data/result/result.json` to the coco website for online evaluation.

**Comment by thy678** [comment]
> The coco-test dataset has no publicly available annotation. You need to submit the `./data/result/result.json` to the coco website for online evaluation.

ok，thanks for you anwser.I will try it tomorrow.

**Comment by thy678** [comment]
Thanks,I get the evaluation correctly.
