### ISSUE TITLE
P2PFormer代码开源

### ISSUE THREAD

**Issue by chl916185** [zhang-tao-whu/e2ec#47]
@zhang-tao-whu 
最近看了您的论文：P2PFormer：A Primitive-to-polygon Method for Regular Building Contour Extraction from Remote Sensing Images，有代码开源计划，什么时候开源呢，谢谢您啦。

**Comment by zhang-tao-whu** [comment]
您好，感谢您的关注，代码在[P2PFormer](https://github.com/zhang-tao-whu/P2PFormer).
