### ISSUE TITLE
About the batchsize and the missmatch of tensor size

### ISSUE THREAD

**Issue by AGanPoi** [zhang-tao-whu/e2ec#5]
Due to my GPU device limit, I change the batchsize from 32 to 8 in cityscapes training, but it got an unexpected error that in the computation of loss, the tensor missmatch the size. I am comfused what's wrong with this error if I lower the batchsize. Or this code only can train cityscapes in batchsize of 32?
![QQ图片20220426164448](https://user-images.githubusercontent.com/35792267/165260909-0833ef48-ce8d-49c9-9c02-4b3d6ba08d76.png)

**Comment by AGanPoi** [comment]
What's more, in sbd training , I also change the batchsize from 24 to 12, but it run very well and get the good results.

**Comment by zhang-tao-whu** [comment]
Sorry, due to an oversight on my part, the training.dataset in the `configs/cityscapesCoco.py` and  `configs/cityscapes.py` was wrong. Thanks for the reminder. The bug has been fixed.

**Comment by AGanPoi** [comment]
已收到 甘伟泽

**Comment by AGanPoi** [comment]
> Sorry, due to an oversight on my part, the training.dataset in the `configs/cityscapesCoco.py` and `configs/cityscapes.py` was wrong. Thanks for the reminder. The bug has been fixed.

Thank you for your prompt reply. I change the config but came across another error. It seems like the anno_file is a tuple and not a str, so it can not use the pycocotools. I check the "e2ec/dataset/info.py" that the datainfo:  "cityspacesCoco_train.anno_dir" has two str 'data/cityscapes/annotations/train', 'data/cityscapes/annotations/train_val'. So how I can solve this problem?
![QQ图片20220427093323](https://user-images.githubusercontent.com/35792267/165420863-b3b5a025-28c9-4cfc-aaf9-dcb13ceada78.png)

**Comment by zhang-tao-whu** [comment]
Sorry, I checked the config files and found that `cityscapes_train` should be used for training and `cityscapesCoco_val` for validation only. Now that I have corrected these errors, you can try it again.

**Comment by AGanPoi** [comment]
After modify the config and info, I came cross another error. It seems like the data loading problem. In "e2ec/dataset/train/cityscapes.py" line 110 to 111: 
        for instance in instance_polys:
                    polys = [poly.reshape(-1, 2) for poly in instance]
The type of instance_polys is a dict, not a tensor to change the shape.
![QQ图片20220428084808](https://user-images.githubusercontent.com/35792267/165654559-af555011-2378-4eb0-8fb8-7413d9149226.png)

**Comment by AGanPoi** [comment]
> After modify the config and info, I came cross another error. It seems like the data loading problem. In "e2ec/dataset/train/cityscapes.py" line 110 to 111: for instance in instance_polys: polys = [poly.reshape(-1, 2) for poly in instance] The type of instance_polys is a dict, not a tensor to change the shape. ![QQ图片20220428084808](https://user-images.githubusercontent.com/35792267/165654559-af555011-2378-4eb0-8fb8-7413d9149226.png)

For the training of Cityscapes, I have encountered the above problem. By changing the code in "e2ec/dataset/train/cityscapes.py", line 110, from "polys = [poly.reshape(-1, 2) for poly in instance]" to "polys = [np.array(poly['poly']) for poly in instance]", this bug can be fixed. And the training of Cityscapes go well.

**Comment by zhang-tao-whu** [comment]
Sorry for the late reply. Thank you for the reminder. I fixes the bugs by changing the 102 line of `dataset/train/cityscapes.py` as `instance_polys = [[np.array(comp['poly']) for comp in obj['components']] for obj in anno]`, and it workes well now.

**Comment by AGanPoi** [comment]
已收到 甘伟泽

**Comment by AGanPoi** [comment]
> Sorry for the late reply. Thank you for the reminder. I fixes the bugs by changing the 102 line of `dataset/train/cityscapes.py` as `instance_polys = [[np.array(comp['poly']) for comp in obj['components']] for obj in anno]`, and it workes well now.

I change this code and training the Cityscapes dataset, but I encounter this error. It seems like randomly happen during training process when I  tried several times. The error occurs in “e2ec/train/trainer/utils.py".
![QQ图片20220606105258](https://user-images.githubusercontent.com/35792267/172086834-c8cfbc99-5357-4c8a-8219-7244a49acc5a.png)

**Comment by zhang-tao-whu** [comment]
This problem is caused by the fact that the input image does not have any instances. Now I fixed the bugs.

**Comment by AGanPoi** [comment]
> This problem is caused by the fact that the input image does not have any instances. Now I fixed the bugs.

It seems like randomly happen that the local variable error.
![QQ图片20220607162256](https://user-images.githubusercontent.com/35792267/172333099-7f1b156b-abd7-4708-a5b3-58990b4c4b4f.png)

**Comment by zhang-tao-whu** [comment]
Modified line 37 of `train/trainer/snake.py`, you can try again.

**Comment by AGanPoi** [comment]
The code runs very well on the Cityscapes dataset and I get the final results. Thank you for your answer! And I wonder when the code for multi component detection will be released?

**Comment by zhang-tao-whu** [comment]
I'll do it as soon as possible, should be done by the end of the month.
