### ISSUE TITLE
How to test coco datasets?

### ISSUE THREAD

**Issue by cuiwenting87** [zhang-tao-whu/e2ec#8]
Hello, Could you  tell me how to modify the size when I want to test the coco datasets, because the coco dataset is of any size.I have try once,but the AP was 0, so I think weather the size is wrong. 
![微信图片_20220517210655](https://user-images.githubusercontent.com/75006745/168817935-1bba90d2-2dd4-4784-925e-bb7d7784bee3.png)

**Comment by zhang-tao-whu** [comment]
The json file corresponding to coco's test set does not contain the segmentation annotations, so it cannot be evaluated locally for accuracy. You need to submit the json file generated during the testing process to the coco dataset official website for accuracy evaluation. The README.md describes how to do this, including the coco and cityscapes test sets.
