### ISSUE TITLE
Generating single image predictions.

### ISSUE THREAD

**Issue by yeshwanth95** [zhang-tao-whu/e2ec#9]
Hello! Thank you for your amazing work.

I used your network (with the coco config) to train on a dataset of custom imagery with coco style object instance annotations. Now I wish to generate predictions for the test split of this dataset for which I have no annotation file. I notice you are using an empty annotation file to perform evaluations on the coco test dev split. Could you kindly guide me on how I can perform single image predictions (object polygons and seg masks for each image) on my custom dataset using the model I trained? Looking forward to your reply.

Thank you!

**Comment by zhang-tao-whu** [comment]
The testing process generates a json file containing the score, label, and segmentation results in RLE encoding format for each instance of each image. But the test requires information about the test set (without annotations), similar to the json file read in during the coco dataset testing. So you need to prepare a json file in the same format as coco to tell the network which images need to be tested, and this json file contains the necessary information such as the path to the image.

**Comment by yeshwanth95** [comment]
Thanks for the response @zhang-tao-whu. I have realised that I need to create a similar json file for my test set. I was hoping there would be a way to predict without this json on images from different datasets, similar to how the visualise.py script does this. But for the moment, I've managed to implement a hacky workaround. So closing for now.
